export const POKEDEX_LOADING = 'POKEDEX_LOADING'
export const POKEDEX_LOADED = 'POKEDEX_LOADED'
export const POKEDEX_DATA_LOADED = 'POKEDEX_DATA_LOADED'
export const POKEDEX_DATA_LOADING = 'POKEDEX_DATA_LOADING'
